---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secrets
  namespace: n8n
spec:
  encryptedData:
    db-password: AgAZ7HSQcznnVoL1Ja4IrloeiAaWVYGem/eBO55PfGbWCEzMAx6XbIDAffRhgrJZNlRRs9A97QLjNb4YzwYOSz5NjkU5xbJ8/TONwpRiPr+OMhlPhQPgJ8x5b/+YXVYdKGj+3/TJapqsmCfET4FLesnw+OLFa4hWxE2BsoMjsoSXEBmVhwffO+aT50um9qamT3Enq2GkNeCZ0JPbN8YwpHETzvHZMab/a/D8GkBDuvhCI00ZN1/w3nlEqkQF6bryCWruAQbwYowv/NCC82RKa3fkqkkA1eLhdsXo3qUcVTvxnu+BprJZ86tkZg0fnbuxKsM6xYgQI45pIdZtL5y3txnR4yoEd0Cfzap+HBDkEKjYQn02W9/SkJDUQv2lIjdCQmGm4n0GyywuuxmHrkYtGYVGXYciesE8REV/MTXijMv1AsnSE+rgiAB2y+a7vIyw2VRNjPt8Dysh3oBfxFvUp1Lrv/VfIa4fI6+LbTgDq6bopn+y2JtneEGrEbuHDvouerKG8Pe9s7gcI+wJoEzBPaTjYGewdTOAQiEuHl/yZdGqI1MJ0K4KSI4+PSmLbNvZKUQXCpqfr6NxPIYbzDma5AHDngwIaG5Tpr6vnS9nfxiytdWKlbJY7uEy2SuOfwflm158Z/kRGHwlhJ09Eu9N7i7L00/KRiuXV3XYfqjWuJIe8sYSTE7t15DhkWMvxU9CjBE=
    encryption-key: AgAuIzA4cZJqnBeY7WahJM30Ji8NirZr8+/6mJ+ci1aJ9ctjGYTqBuQhCuAygb0/ApIa/GqE56J0W0fJFhPR4OOPzDy1MtDu8t65Rv0HMq6rfy8nGSec4r1uaeuPpB7uDwWXwU9aoGP7+hKc477Di59bcu6zpqRnqyJxRyHBxVT53qVhSkxSmvG/zgZDbKup3X4JGIAmFZAF8/py9ZB8frUlf+JUAnUqMCaDFVpxCX5DHGCW+cHGmfgReXY/mYdrbqME5lJlyQy2Tj1Rciuk7eltYSPhl+TgkBTcUaLG778O8iKqeKD1v1bUIjeEFC6dBuNaX9dYm1uiP5rgPr3s232e/9qvheuWoWCzAXpo+mYUlm/V66SGAUploUgc+BU8YPCICiah8dL++wrohm4Yl7ZaQDwSSGcT/tH/xGj3LgNL6ecbPlPMSuPzKskEUN5+e3dMVsLSi7AwODkP6mPCDze+BTcSOq1LbrsLSjnQwtg9AIjfcJnrbIimxxvJNbkSDCQ9ubhOkhLBA7oTelsPrxzWnh4KmJEu0dctixAQcPlzUVE2bqdOuWbafpsXkeelPhig28cC6nUKFxcLWh4k0IG4w+ea7/lH8P1bPKJ8EVBmdd18dhE0hF0ZlYbZsZUJqvA2ZZpPH4Jwz/6x4f2WExm5ywxgaqUtNRV+oDsRd6Ie2XK7Mi22xKFKO+znCrpIYJA=
  template:
    metadata:
      name: n8n-secrets
      namespace: n8n
