---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-runner-token
  namespace: actions-runner
spec:
  encryptedData:
    github_token: AgBFZR2Fqa/dJQyy4rA0+fBl2QQ0ZGh1KTbQMW1sdLn7XiELHDEOTQdUNi1CZr++/43vUr2ebt5HqyYG3uqyNewahGlccxe3/60Incc4gi3WwPzjZotz8eSoH7z6zg7SHKsCAu/Vexe9zsShRB0WucZ6qCwSs2Ae/iSrtGvcNqGaEYP3NP46BTA3vzL3XHqzSpzWincvE+Sh48qAqPVdnigYJk9zP1/GIYkqduLwYfXwUqtlRNqxYeC/XYqWmp3vuXs1TtO+wd5CFwtTlV45L8ayb4WNndWeky14nnSzxtjTxJjszpo5VGJ7yvqXk9BBAmjqku8ZbSDNN5Nf/o2yvBB199vzeer4ClxpKXo27mvgGUctCU8Ouj8hlA+Hjob+A/odEix9FxqHvtoSaebsCXOKpDkMnPDM722i0NtjWZYhvuhBmsDpl6rtVe7tr4r8tBu55s3VE7q8JqG1Fclw69/EgRdnNKvlDyBnTZhBug4iT9mOmx8lAw4twjai11r2WqWrgxsM8wJWoO2Lvyjpa3z+vHJkysYchIgfMI43VDFKXGsRUeT67HhZTAzmn/j+jxBMVuG1JXR7nySxCDzSkNX+XiaTAXF3+Wuk2PEDoIiUTZ5OBzy3hg4xK3ncOdNZxIv8TH28gguR7LA09OU9c+dTYbuDwRZzeM5xJB45KEoJpCCIwwYPSjQ5DtyKdIVhYXkZdezGLJMdSeF54mTFCahbXT2nfu72wcePmN6/xyUWk5k7EJ0civzi
  template:
    metadata:
      name: github-runner-token
      namespace: actions-runner
