apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: telnet-server-pdb
  namespace: telnet-server
  labels:
    app: telnet-server
    app.kubernetes.io/name: telnet-server
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: homelab
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: telnet-server
