---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: outline-secrets
  namespace: outline
spec:
  encryptedData:
    secret-key: AgC7ZVRCJyKnG5LlJAtReFI9+IbA1e2IUgFd5bnlVBGKlfi0KcYrM9YZpXQUB6rXIsY8J+QesORkZm8aA7xpvqw/WflN3gAg6DdvGJLLOL+s1fCU6Gcas+m7epy1/7QCFsE50NeVj9aT7DoLf4YES4ypSRUCaTENZpWDhDYoqT7bSAn5/VDSdfSKz0AhZMdxgpqEMzb1GuygxkISRAN4W9ER9gR6Dk3hKlGQ+0ESUl8arJVtRus9N2YzzaAOzKJ4hCNscEXaQlV6vRueWxIG7FyGWhDc0JX3wTv/DGXYWxMqbO1WxNWMiv/znQYQ408A9FTCPrfaNM1oOUjcJ6rsKL9lCS4hJeD0SzwqStUFNhksikFKSbLC2U1jMweoNDhiYNj6GkbUZ0b18m2hTEb3HiVUIqsVi2rFHmvK6vgGvAw89dvbg5BwZ44I/GLxViD91FAbvB7f1/bpjbboC8zs/X3D93zUDtRHvtSo6b99lFcbSM7k5eHcBLVOyNgDLTjaNGaQdgj6a47F6biJo29d6d/cfjv+kKZWnW93fiiJhKcpH9+Ja0gkkuCqWM+wmhpeQZXLfDm1Ffzr0/Tvyrl2jYkbXEc8jeul0uZKd1sOl6Hj3QdJs/GxEb3aKJyLNHSEtK9AcaaaCBLiBnNifnFnEn9iwqRnDq1ag1JW6oJgBka/YFyD9IG/uLX/6IYKO882TLc=
    utils-secret: AgAUC5shgyGezYPicKyg8eiBl4uMXNyE3eXkRosZkcOCwyOecW3P7qLYiWrfNNU9dOuX5XwXyBIs4auAX/6Myl8eoXauccRjK+SQmQNl++5i3UV8Si2WzoZNJmRuTNB2XppZ05hURMsqlR9/mlJsB8G3t0Ic5zMQAzBnjEUTeNScsHFjdiGaYP/E8JVnIyA7GRGBGqVeBRNhzwfeE7wcCgHoDnJ0/8OYiZXUg/YxWbFp6NI0Ta70lO/X7Nm72jHhVTZYJDuoPu8mBycomBkWoZmt+QXRreKEAVsEh+SnNRL4PmgSgHyseI3fo1cASo1qdMNUbchHEMJZcJq3Hr+5xO9UN2W9qUCCwMwfMeMIgPiJ8w8neBh3UF0WDo/xnXfiRjb3ZR0gITb2PqP8EsH5IXCfg7uF780R77sx+oSEeJ1mfcCPIoj8wUYcRi2MKNUCMBY+Nanzz9scHx0FK+LQy0wJKsDbDJ+ZqwGDCTvIqLTCDpSzPQlIvvx7+Ss51kU0QpKcIQzJI8zDz9O2SruhhGsYMAZNhY0+5f8NmHKiHA4idIYpr50HZDL1uNMJXoxmZyKNNMabKKPR8M81aRsMYaFZom8vmhIaEk0zTkfaPebuDsmTq3kkNGJpLFCUs+JWjjpkikIscjHjjmHsRyXNnHzM44sNZxx0RiMOIaieujDF5MDYQmjZvwpWzAHBL5TvQos=
  template:
    metadata:
      name: outline-secrets
      namespace: outline
