---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgCArugmafyTwIV5TDOSSF6/OetMibSPzPLdEhUL2QZX37Doxh5nIN7QmuSAoUu9aEVTLoQipQk9Eb3RX8Mj3rYwbB+Lad7ROgHbrQ6Qy1jd2e2fBxIRwmSPOTAslXjEzhOW2vMgHekBGG8L44TBnDxvIDv55hMfw+0xCVLApo+p8t6lQSM4Sw5lpbUP8v0XH/+RNqU2tP2gx/IoZ9vSx8YEzXDsUimRuzaB0qykH8dXHsFO665ohQcQ2is9aoC64e8k244IkX/KGWqUgHzO3z4JTpSKajmlajV48z5O10+PP6thSRDSItc555cL6xFJ+entYET1dtjhzSMR/6UPmYncdzU2Yq9qVvi1ZU1QTc7vgFTVBySnMRlLFunR0EOlnC4WIz+CFEfPzXJd9JhFa5AlKx5Id7izBA0Uyye6apBRFwu9ZlGNr8WKWUEMkVvUawCENVgC/O6LgAqkBaHflQHtrazknU+biAo+J1rM7USYhiXCZmWqxEYzpKD1ndDOiMe7aAZ3lPd77Fhk9024RK4qWYkWecqO1FellM/MH8pRGVRGbNZnphnjWVjvD11wycItU2RvTDPhNeYCKaN6HKar/8nMPbEUvsK316eKCOYfnJOX4au4TTNhZioG8KJ8IqjJoEukqjuSKXlGOyzs+PHIFM7fJh0ovBEZ4g0ULNAH05gS5bNPduUds7eECkTfFTI9MEDlAs3Ait3p40mWpobSs0viDGIUbIgyTThcFvJ4j90GWOb2S7YL
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
