---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgBjYvo+9K0dDl5IMBlU8mfTtKrTNQKh9Q6XVvJp/WL/M4+THO7Q0JmnDCi9iYAXk1oP8Vf+wwVhLOPLCq9qdR5yvoWg0Mz1S4rJiMKTJ52Bl2LjlTWa8LvfHG27STiQQW5spBD46ZxOkjvXGHPDHHn8LVFvX+MADR34coPxcR66WZ3oheXaHAUyb+VA6Mqh9yvka77OLBhNl9fdS0riwb3PkavJDvd+Qe7M/WQJlGJ1mExVfuUwdsGi5exWPOzMe+MBV6y/XaOej0RVDoP3ryLj5rIp3OJAomJGoBv+RSo2HIAfgfmQvFQnrPnxnZun64KYSSTH3bqaccILim/touCcQK5eoDLD08jZKPlA/XQDZtAoEMfyzi1MvKXPUSPNYiwvaLwTMpfNFREIquGp4ebPzekmpN3yJAAi6oY+wPEtwUIgbnK/Om9u9F/MfzzS5sp4ty4IK6yOMNz5+JaJRnf5GMbspjv1HipVJONs/fryQfmhMQmnBCoiSJBiuGrq86+wiJmmws7vybqgBF/QlcuufCvkXilBStzvfotjkGu7KlJSppAgBvu/tRBTsYqyGfDzmK/SxGQwtBbyA4vKKqPNWELMwRoFXNf+BLchHrgy1xlkMr13tCRxOXISoccL1yhcCMxWnkYQty/KtJD0Fo+MPpWFMNtfecVw75M0pS07yNm3IZPxvy1ec76KuNNNLnA=
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
