# Longhorn Recurring Backup Jobs
# These create automatic snapshots and backups of all volumes
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-snapshot
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  name: daily-snapshot
  task: snapshot
  cron: "0 2 * * *"  # 2 AM daily
  retain: 7           # Keep 7 daily snapshots
  concurrency: 2
  groups:
    - default
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: weekly-snapshot
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  name: weekly-snapshot
  task: snapshot
  cron: "0 3 * * 0"  # 3 AM every Sunday
  retain: 4           # Keep 4 weekly snapshots
  concurrency: 2
  groups:
    - default
