---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCRurFPHDBTLQpNmwuQK2X/TrhGhNRlSKZ05hjkzU6OjIIKpmsk/Rw7/Hn5eb6wsD2utAIG6tyffWCl3FnKim4kX0mcJc01YnGLNJjjIfGS2b5/JIz4mtpDTUOqroMbO3Hlh3e/lSSS3LD9wta1o2JmhEJoFYCjvEVUp3J4dDRbq3e7RdG6o4qA6uneO/aTwCB4rGYNJ2+tggTszhnzYB7Mu9lnVIyYjN0QCn/x2gHs15ScPETfBI7Meaa4qTK0YkR/TrEDnOa04D7bdPVQ5KPpUhQBcVmbxa0uR3O9luOPti/3sbMrt8TQVCDsmsuEYTI6CJjzx4mr/6A2d2kA/7pMDbToppY+8LPDaOKYqLGZVfdUfsugcPAav/m+y7RY9+dBo+3FVpps2CTmqLkmhiiJN0ARQYzxw6lk8wc8NZr6CcGVDAp1N2sR0efYwLw96yzC25p1dFuhm9et0jBIwV+AduA6kfDeQniO+gWITxxrXz1kEUrjWcI51oUbsLA+Vom12A0nJnrU39IGQpHDCiAtjjBRj58lv9Gvz1Xn9XlxMRrICV2JVh0vEZMAGorXP/5i/dPUcz8br3MkbG4NneSMOznnfjsnpbSbQTrqptkfJJrWHbSNnf2vVyh7PrKA21pNomQ7dToAJ4SkVEZwUv2LnOG3AY1QrTYyRHvY1eArrw9Dem9w674FsqQnFkyhDjI=
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
