---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCcpPl2bWIqSUJIL49EWNPzsQHt4yxmbe8ySqhiqEjQlmvRTd/pyZPsbicGjvd0zmVoxFa5Vnvx/0EgVTH9yVSAL5IwzK71SFTJcrWXtGvUxd4pnVC7cD5Ogyq2utK1CdxptQpmRQPPXN906M/RewsCSdOGnUy8a2/opK04hskgDFNF9wpG/P/CcKitenU9UbNdZr29PbcfiuVSRDhl4hutBSx18qx6e7eJRZKOvyAtVJEsZRBdqFh8CpzmG8BY2V9/aflRmz15y1S3Co3s3peW4JXT9pB+akq1RtXijqevZkZMVq0R2yHEQ5ZleHUsLAlJjmzLFqUUxlK1W05gTEN6o3BNZbvaAuoiWH5U9DBrCaCLcxZQeSiZVUSjLqzkJ9m6hpjynJW/EQ5tMVrSu6Zsg1MKxM8QXC0ZkTDKT/t3WW6magd1q3SiotObuC2Kgc3ECQNMJjkcRGQuOzu28u34LsXDXVKEsxUAaiRwGtu6BmOpPoUzvHIQ6xw0Vnwn0rj4bzyMzlvvkaL/m+oAhloXnzPm77ZciAjzqL5y+0OPz9efFsJ8pxcQ6ZjwC7wxFjvUjmvdw0hm1kufC0nxa3YE3gvfJALm8RAX2S6EpnLT7bCyZnudQVdbquM+ehfTDDVrAFOcX8deQp9wbQa1esNLlkUu2KCx2CX7EZXwkDshayats4djGvwyRPQJcnC5VV9qi+YvRgVMmo4GIfq9kT/APSt1CgB7BLByczwz2lasRIgW9q4PwIdE
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
