---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC3OU4YJa5zjFB3R4Fc+hWIqgg1ewwSDrczNKESabn2lEH+46ff3V/3YjMJSJXddKIyvVQLEYJWYaqNtNJW+pbbGOukxb2end+qlMzHnCrZuY64u9psiGNNzO64btT8KWZb3mpRIRLWQ3FZK4RRgzz/fibfxH2TfdwfqGGZBfWYbvpYs6LZMaJ7kgb6lWWrMwDVriubKxpSaHmqOvscvpWib3bNsOz5bxTXM37YRx2sN6LOrrHZL/jOGSYbklq/nqY8gS81dPFJDpxAMMh/VKdG6oyEQj9KxoVtlcbh6m4JSpCfkGPGtPqVzEMtLlRfZ6C2Dw6L0NTf6MF93xCL6YIn67wvq0y27r/v79Ua+0wlimvS9ma23Z+dO79Cw0WAy4j4VO0QqJUMG+5zm2IZfZNFYKnqnZSmJX0sbUoZHZaG2pvvRiK0tC7z3bLiOSe/yT2rOf2TxnjqPshkADbcOQnWfTDpowmbe4gxr15cNgeL4O15QF8q5v3/43uUyle5gV4JrtgefAM7QIP1v9y8/Q8SFS4Riu6hFK1/wbcDa17ugNEBhKJl4iDg5OQEDvmaePjSZ/FQnJn599PlUJMUCL2Y/jAaOYtTQBT+oFiXVQ313fWQg4l6wTUzVqEdWvLj/VqjoOrR100kS1NLhAn8Ul2ETtPqw1bP08dp03VQFoB5z0+aXlfKX0TnjAzeevUYzalBXBqtKujvljcLrnZO4d5IDaEP/nEYPNM18rQanJzqpSJ2FQ3dauPk
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
