---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-secrets
  namespace: open-webui
spec:
  encryptedData:
    secret-key: AgB0gRNfotRmeOlISWEW1+Jmzn5ZGddEPaQPUV02FkfHLHf+uWQJveB1saKeWY2PvlNj45fBURcyWy6jg3f2fZfJKMLWbsLSM4HPfkJnqayB9AkA8oaxtucvxOIiIqLEIiF4Q9chIxOfznzy46F0AXmYyNYjsC8RV84hYI13iZ0dRdsKtZqHNHJsOHVPUpuOQL6S2SMnlzceQxhQXmFdaPJ6xUDZmO3ufpN1C7vJpNNDpUQQdoA78f5Q6LVmavHnoJIx/sGa8JFSFjE+1E1t++5IAn6kxEI80Y6ZW8XW3k4GVh8fSpuHrnBMCte2FkSdROmqe42F+qcufSm3LkpqllGkb+PX52izKwvdYAVkW/+GCRLtKHS0l3WhpjSrlYrnq6CusexCZ0TQeltZHETvDvIQ0gjTINSk1nCRV8WfdW/HfsLsFgOjNKlkkSligOWTQubYFAuYT0znhFzE0IML8phCnbxSLYDhcGZTAruhOYH08T27UuY56WOl8IUPkuW0l24QpFSODhOpROfb0T+9c4371rGmxHkiWZOHribdGtKu65aupU8GZO80Z/SVkS9RLEe/hSh/LF5aEg5WGiXaqD8LetdQZdC9TSJrWGGY6kYmhZqPSE770GuHPft5WkIWe0km/tSk7tfOzb/5uIpCtg3HYCNi4z8qkS+nJo7L5kXD0jnwGgYFDYU5ViVuW/I/hBI=
  template:
    metadata:
      name: open-webui-secrets
      namespace: open-webui
