---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.authentik.clientSecret: AgCdYnFXvri8cJnhYpzTC7iubSF4rpEJzV7wPVf2bHuYs8N/4zi6zH43AOg76xXDDKkaMqUmfUfhz//Ha/zsEmL5DT8i6wBbUygFnAQh+tCtSG7PiLcR4dkg+D5CSmRG/7jDw2siia3tyUDa1mGFLtmE3WBWLMNSh5S40S0soOPuvZQw4xt3BFNHd4DkzfCvuRTPZB8cFAkTOokG0WTqdxMgaKBd49pWJxF+d3nsdXuH5MY+d3gl3MHOOJ1PMquKC4922bVXVqgn00EPxp0fedrCi2yURJshXhRJqVfDSVKtTHRhrJOQumloQI5tPxR7zEIptGfJOWhoqVLVfafU8FFqdyHvbLGYe2yHueLtUjibeJqYDGA4uhhx0goXLBgE4w9W3fZr2u7BFja9esg+2ZeLunkqwiPeS48KhfM7UBvxgFFeUCY95Hyu2iOTTDbew3PHec8q6qNzbZd+UAQ/+NAs0adJGfhozUZ1qv8OWfTSC21z6zpAPJ+4B0Qp67j4FU0L06F8nft5wzl8wjYAwF08rlHX2OgE73xqtyjPpclF0lePq58AV0UMWm/W04kpxI5rmSOQytzyg+GvuCz4169+O7FHFOWdOkECNS2v1c/KMhvc3UKxTshViT2GzJIwRDjqG/+/ypVyi4DPSWTEYlbswOkoiN6RW+gYbpsjeI+/vh6525lQzRLBAsXRfTlbaGIi+etaK85vUS092kN3Ol0BotpMNMBVGT5rdjbtCF7Qa9bjANwAJvlI9KCJY8zyHQuuD/RVgtcA49yUJjOUE1887fkByhc6PLw8lYi0OdhcozlVtP+OsNTQQNjz9L3JK4tm3L5YiDjgvO6sTMVQ/vDWCnNpnfb7fQJS5swrNMgG1A==
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
