apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
spec:
  encryptedData:
    oidc.authentik.clientSecret: AgBD7v1z64H5O3gaVWIwu16uI6VPtt1iL+crylHD+lIkZGlIjF0z5iNlpESgK9vcUtdnv4dOwVhYnzMQ0YPXOh1WmRn/Wa/mP5MzsqmiN14/6Fcaa7KR16cPMLRITIRukTIlUMXijUHgNhlWLtSf5n5eVAxOowGfkheM29oWMu7Rubi0sYbb5DKPzrKmIMJr4uEZpJiBjr0Qi6JisjhE+H0N+fduf4tOJ+l0M9i6NDCk8PtLEJcW/7lr1B1c4kyXL53RtDRy5uy/VIoGabBzj9gpM1wJ3Q6kgEQPnMvj0sN13+JNQERiecSfqB1Zzx+bCQCVUyJgSEsYeWxmPpi4q+0KIDJxPViqdhT8wFyl4e/nLv2xxGSRPjPRZwXQT6xFN9qgLJ/JaPQWjO/PJgPNb8cmdZdyIoMONBcgMc7w14KN0bwdBFWHUmKLakN+Vqrfcvq+48HdD/iFfTr3q0Vj0dkA5jHkBDOoR88cmUQRYoC5enZdQ7yCKuD1ZbW8c9twP7civhTEZI7ffykpH+FB4sR5vCR+1CVS1FtGi13VQQool0Ru278RjAxrr49wZb3p7c6bs268teuzE4ObI3E9laUrTcsFQeRd/1GHrcqhlcy2bDAq1lM2akZBZ3QadHxRcEPM2Xwv04JsOTZE3FJXjgh5uSTK7niMFO+d69k7reRZJD7kuYWpGcfTvhaWI6tF5gUmg2JJQbd6ae5Czhq7TdpHXos8inT0f6ku4FLb4y/sdCHEteM8kCptFn6ErvTrP6ykgpHGz1ocukXPuMqnqRTF
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
